### ISSUE TITLE
PED file published failed Kinship + not overwritten after re-run

### ISSUE THREAD

**Issue by melferink** [UMCUGenetics/DxNextflowWES#25]
PED file is published even if Kinship analysis failed (due to i.e. mistakes in PED file). 
After PED file correction and restart of NF workflow, the new PED file is not published (old remains in publish folder QC/Kinship/)

**Comment by rernst** [comment]
We should disable cache in `SavePedFile`. This will force a restart of that process when restarting the workflow.

See: https://www.nextflow.io/docs/latest/process.html#cache
